name: "Deploy to Google Cloud Run"

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE: test
  IMAGE_TAG: latest
  ZONE: us-east1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Docker configuration
        run: |-
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://$ZONE-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/$PROJECT_ID/$IMAGE:$IMAGE_TAG
          build-args: |
            HTTP_PORT=80

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: gcr.io/$PROJECT_ID/$IMAGE:$IMAGE_TAG
          service: ${{ secrets.GCP_CLOUDRUN_SERVICE }}
          region: $ZONE
          platform: managed
          allow-unauthenticated: true
          env_vars: |
              FOO=bar
              ZIP=zap
