name: "Deploy to Google Cloud Run"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Docker configuration
        run: |-
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin us-east1-docker.pkg.dev

      - name: Build image
        run: docker build . --tag "us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/test/test:latest"

      - name: Push image
        run: docker push "us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/test/test:latest"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/test/test:latest
          service: ${{ secrets.GCP_CLOUDRUN_SERVICE }}
          region: us-east1
          platform: managed
          allow-unauthenticated: true
          env_vars: |
              FOO=bar
              ZIP=zap
